name: merchant_mobile_app
# TODO: Globalize.
description: An application to help merchants staying up to date with CSB's service outages.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+33

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  flutter_inappwebview: ^5.4.4
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.2
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  cached_network_image: ^3.2.3
  intl:
  dots_indicator: ^2.1.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.0.5
  launch_review: ^3.0.1
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  timelines: ^0.1.0
  encrypt: ^5.0.0
  device_info_plus: ^8.1.0
  flutter_native_splash: ^2.2.19


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo_csb_grey_512x512_android.png"
  image_path_ios: "assets/images/logo_csb_grey_512x512_ios.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_csb_splash_screen_512.png
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/logo_csb_splash_screen_512.png
    - assets/images/background_epaync.jpg
    - assets/images/background_tydoc.jpg
    - assets/images/logo_csb.jpg
    - assets/images/logo_tydoc.png
    - assets/images/logo_epaync.png
    - assets/images/logo_button_calculator.svg
    - assets/images/logo_button_TPE.svg
    # FAQ
    - assets/faq/pos_term_telium_fr.json
    - assets/faq/pos_term_telium_en.json
    - assets/faq/pos_term_services_fr.json
    - assets/faq/pos_term_services_en.json
    - assets/faq/pos_term_tetra_fr.json
    - assets/faq/pos_term_tetra_en.json
    #FAQ Images
    - assets/images/catalogue_TPE.jpg
    - assets/images/pb_impression_ELC.jpg
    - assets/images/pb_impression_ELC_cartouche.jpg
    - assets/images/pb_impression_ELC_changer_cartouche.jpg
    - assets/images/pb_impression_ELC_encre.jpg
    - assets/images/pb_impression_ELC_languette.jpg
    - assets/images/pb_impression_ELC_papier.jpg
    - assets/images/pb_impression_ELC_placer_cartouche.jpg
    - assets/images/pb_impression_ELC_rabaisser_levier.jpg
    - assets/images/pb_impression_ELC_repo.jpg
    - assets/images/pb_impression_ELC_reset.jpg
    - assets/images/raccordement_lecteur_cheque1.jpg
    - assets/images/raccordement_lecteur_cheque2.jpg
    - assets/images/raccordement_lecteur_cheque3.png
    - assets/images/raccordement_lecteur_cheque4.jpg
    - assets/images/carte_piste_LECTURE_PINPAD.png
    - assets/images/carte_puce_LECTURE_PINPAD.png
    - assets/images/carte_sans_contact_LECTURE_PINPAD.png
    - assets/images/TPE_Move_5000_B.jpg
    - assets/images/TPE_Desk_5000_EM.jpg
    - assets/images/TPE_ICT_220_Fixe_Telium_II_IP.jpg
    - assets/images/TPE_Ingenico_IWL_250_IP_3G_contactless_base_chargeur_3G.jpg
    - assets/images/logo_jcb.jpg
    - assets/images/logo_amex.jpg
    - assets/images/logo_contactless.jpg
    - assets/images/logo_jade.jpg
    #FAQ TELIUM
    - assets/images/faq_telium/changer_rouleau_TPE_TELIUM.png
    - assets/images/faq_telium/raccordement_mobile_alimentation_TPE_TELIUM.jpg
    - assets/images/faq_telium/raccordement_mobile_batterie1_TPE_TELIUM.jpg
    - assets/images/faq_telium/raccordement_mobile_batterie2_TPE_TELIUM.jpg
    - assets/images/faq_telium/raccordement_mobile_ligne_telephonique_RTC_TPE_TELIUM.jpg
    - assets/images/faq_telium/raccordement_mobile_TPE_TELIUM.jpg
    - assets/images/faq_telium/raccordement_PINPAD_TPE_TELIUM.jpg
    - assets/images/faq_telium/raccordement_TPE_TELIUM.jpg
    #FAQ TETRA
    - assets/images/faq_tetra/fonctions_debit_TPE_TETRA.png
    - assets/images/faq_tetra/annuler_icon_button_jaune_TPE_TETRA.png
    - assets/images/faq_tetra/annuler_icon_fonctions_annuler_TPE_TETRA.png
    - assets/images/faq_tetra/icon_paiement_TPE_TETRA.png
    - assets/images/faq_tetra/icon_tel_TPE_TETRA.png
    - assets/images/faq_tetra/annuler_TPE_TETRA3.png
    - assets/images/faq_tetra/lecture_carte_commercant_TPE_TETRA.png
    - assets/images/faq_tetra/annuler_TPE_TETRA5.png
    - assets/images/faq_tetra/crediter_fonctions_credit_TPE_TETRA.png
    - assets/images/faq_tetra/crediter_TPE_TETRA3.png
    - assets/images/faq_tetra/crediter_TPE_TETRA5.png
    - assets/images/faq_tetra/paiement_accepte_TPE_TETRA.png
    - assets/images/faq_tetra/duplicata_TPE_TETRA.png
    - assets/images/faq_tetra/duplicata_TPE_TETRA2.png
    - assets/images/faq_tetra/duplicata_TPE_TETRA3.png
    - assets/images/faq_tetra/journal_TPE_TETRA3.jpg
    - assets/images/faq_tetra/journal_TPE_TETRA4.jpg
    - assets/images/faq_tetra/journal_TPE_TETRA5.jpg
    - assets/images/faq_tetra/journal_TPE_TETRA6.jpg
    - assets/images/faq_tetra/journal_TPE_TETRA7.jpg
    - assets/images/faq_tetra/menu_2_TPE_TETRA.png
    - assets/images/faq_tetra/menu_TPE_Tetra.jpg
    - assets/images/faq_tetra/menu_TPE_Tetra2.jpg
    - assets/images/faq_tetra/mise_en_place_papier_TPE_TETRA.png
    - assets/images/faq_tetra/raccord_TPE_Tetra.png
    - assets/images/faq_tetra/raccord_mobile_TPE_TETRA1.png
    - assets/images/faq_tetra/raccord_mobile_TPE_TETRA2.png
    - assets/images/faq_tetra/raccord_mobile_TPE_TETRA3.png
    - assets/images/faq_tetra/raccord_mobile_TPE_TETRA4.png
    - assets/images/faq_tetra/raccord_mobile_TPE_TETRA5.png
    - assets/images/faq_tetra/raccord_mobile_TPE_TETRA6.png
    - assets/images/faq_tetra/raccorder_Fixe_TPE_TETRA.png
    - assets/images/faq_tetra/telecollecte_manuel_TPE_Tetra.jpg

    # Security
    - assets/security/public.pem

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
assets/images/duplicata_TPE_TETRA:
  png:flutter_intl:
  enabled: true
